name: Publish FriendlyResult to Nuget Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/FriendlyResult.csproj"
jobs:
  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Package
        run: dotnet pack -c Release src/FriendlyResult.csproj
        
      # - name: Add-Source
      #   run: dotnet nuget add source --username dnslowlavelcode --password ${{ secrets.FRIENDLYRESULT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dnslowlavelcode/index.json"
      
      - name: Publish
        run: dotnet nuget push artifacts/*.nupkg --source "github" --skip-duplicate